work_dir: ./output/ctr_JB
pkl_name: ctr_JB
# feeder
feeder: dataset.feeder_JB.Feeder
train_feeder_args:
  data_path: dataset/save_3d_pose/train_joint_bone.npy
  label_path: dataset/save_3d_pose/train_label.npy
  p_interval: [0.5, 1]
  window_size: 64
  bone: False
  vel: False

test_feeder_args:
  data_path: dataset/save_3d_pose/test_joint_bone.npy
  label_path: dataset/save_3d_pose/test_label.npy
  p_interval: [0.95]
  window_size: 64
  bone: False
  vel: False

# model
model: model.ctrgcn_xyz_JB.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
