# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_bone.npy
  label_path: ./data/train_label.npy
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False

test_feeder_args:
  data_path: ./data/test_A_bone.npy
  label_path: ./data/test_A_label.npy
  debug: False


# model
model: model_td.tdgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'
  in_channels: 3

#optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: 0
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
warm_up_epoch: 5


work_dir: ./work_dir/wrj/joint
